---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      name: {{ include "chart.fullname" . }}-tcp
  selector:
    app: {{ .Release.Name }}
