name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Lint ArgoCD manifests
      run: |
        dirs=$(find . -type d -exec test -f "{}/helm/values.yaml" \; -print)
        for dir in $dirs; do
          find "$dir/argo/" -type f \( -name '*.yaml' -o -name '*.yml' \) -exec yamllint {} \;
        done

    - name: Lint Helm charts
      run: |
        for dir in $dirs; do
          helm lint "$dir/helm/"
        done

    - name: Validate Helm charts
      run: |
        for dir in $dirs; do
          helm template "$dir/helm/" --validate
        done

    - name: debug
      run: | 
        echo $dirs
