name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint ArgoCD manifests
        id: argo
        run: |
          dirs=$(find . -type d -exec test -f "{}/ci/values.yaml" \; -print)
          for dir in $dirs; do
          find "$dir/argo/" -type f \( -name '*.yaml' -o -name '*.yml' \) -exec yamllint {} \;
          done
#          echo $dirs > /tmp/dirs
