name: Security Scans
      #echo "$dirs" | while IFS= read -r dir; do
     #    echo "Processing directory: $dir"
     #    all_dirs="${all_dirs}${dir}\n"
    #     done
     #    echo -e "All directories:\n$all_dirs"
on:
  push:
    branches:
      - main
    paths: 
      - "**/argo/**"
      - "**/helm/**"
      - ".github/workflows/**"
      - "!**/README.md"
  pull_request:
    branches:
      - main
    paths: 
      - "**/argo/**"
      - "**/helm/**"
      - ".github/workflows/**"
      - "!**/README.md"

jobs:

  security_scan:
    runs-on: ubuntu-latest
    outputs:
      image_repo_tags: ${{ steps.parse_directory.outputs.image_repo_tags }}
      dirs: ${{ steps.discover_dirs_b.outputs.dirs }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

 #   - name: Install Trivy
   #   run: |
     #   curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

   # - name: Install yq
   #  run: |
    #    wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /tmp/yq
      #  sudo chmod +x /tmp/yq
      #  sudo mv /tmp/yq /usr/local/bin/yq
           # echo "dirs=${dirs}" >> $GITHUB_ENV

#    - name: Discover directories
#      id: discover_dirs_b
#      run: |
 #       echo "Discovered directories:"
 #       dirs=$(find . -type d -exec test -f "{}/helm/values.yaml" \; -print)
 #       for dir in $dirs; do echo "$dir" >> $GITHUB_OUTPUT; done
        
        
    - name: Parse directory
      id: parse_directory
      run: |
        dirs=$(find . -type d -exec test -f "{}/helm/values.yaml" \; -print)
        for dir in $dirs; do
          image_repository=$(grep repository "$dir"/helm/values.yaml | awk -F': ' '{print $2}')
          image_tag=$(grep tag "$dir"/helm/values.yaml | awk -F': ' '{print $2}')
          image_repo_tags="${image_repo_tags}${image_repository}:${image_tag}"
        done
        image_repo_tags=$(echo "$image_repo_tags" | xargs)
        echo "image_repo_tags=${image_repo_tags}" >> $GITHUB_OUTPUT


#    - name: Debug `values.yaml` Files
#      run: |
#        for dir in ${{ steps.discover_dirs_b.outputs.dirs }}; do
 #         echo "Content of $dir/helm/values.yaml:"
 #         cat "$dir/helm/values.yaml"
#        done
        
    - name: Debug Image Reference
      run: |
        echo "Image: ${{ steps.parse_directory.outputs.image_repo_tags }}"

    - name: Debug Image Reference
      run: |
        image_repo_tags="${{ steps.parse_directory.outputs.image_repo_tags }}"
        for image_ref in $image_repo_tags; do
          trivy image "$image_ref"
        done
          
        


    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
    #      image-ref: ${{ steps.parse_directory.outputs.image_repo_tags }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'



    # docker scan "$image_repository:$image_tag"

