name: Security Scans

on:
  push:
    branches:
      - main
    paths: 
      - "**/argo/**"
      - "**/helm/**"
      - ".github/workflows/**"
      - "!**/README.md"
  pull_request:
    branches:
      - main
    paths: 
      - "**/argo/**"
      - "**/helm/**"
      - ".github/workflows/**"
      - "!**/README.md"

jobs:

  security_scan:
    runs-on: ubuntu-latest
    outputs:
      image_repo_tags: ${{ steps.parse_directory.outputs.image_repo_tags }}
      dirs: ${{ steps.discover_dirs_b.outputs.dirs }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
     
    - name: Run Trivy
      id: run_trivy
      run: |
        dirs=$(find . -type d -exec test -f "{}/helm/values.yaml" \; -print)
        echo "Discovered directories: " $dirs
        for dir in $dirs; do
          image_repository=$(grep repository "$dir"/helm/values.yaml | awk -F': ' '{print $2}')
          image_tag=$(grep tag "$dir"/helm/values.yaml | awk -F': ' '{print $2}')
          if [ -n "$image_repository" ] && [ -n "$image_tag" ]; then
            echo "Scanning image: $image_repository:$image_tag"
            # Run trivy and capture its code
            trivy image "$image_repository:$image_tag"
            trivy_exit_code=$?
            if [ $trivy_exit_code -ne 0 ]; then
                echo "Error: Trivy scan failed for image $image_repository:$image_tag"
                exit $trivy_exit_code
            fi
          else
             echo "Error: Image repository or tag not found in $dir/helm/values.yaml"
             exit 1
          fi
        done


